### ISSUE TITLE
Is it possible to use Nivelir framework in pour SwiftUI project without any UIKit navigation primitives?

### ISSUE THREAD

**Issue by shalom-aviv** [hhru/Nivelir#106]
Hi guys

I have reviewed some code samples, and it appears that Nivelir is a good solution for projects based on UIKit. The partial Swift UI support is an additional feature rather than the main goal of the framework.

Thank you

**Comment by almazrafi** [comment]
Hello 👋

Yes, at the moment Nivelir is focused on UIKit.

But our project started migrating to SwiftUI last year and we plan to focus on the full integration of SwiftUI into Nivelir by the end of the year.

Thanks!
