### ISSUE TITLE
Переключение таба

### ISSUE THREAD

**Issue by LevinIvan** [hhru/Nivelir#107]
Привет. Как через нивелир можно достать TabBar и открыть на нем второй таб?
topCotainer у меня RootViewController. 
Пытаюсь найти TabBar через container, но он его не видит. 
<img width="444" alt="image" src="https://github.com/hhru/Nivelir/assets/100189059/dbda8c9d-745e-4cf3-bf3b-c506ac4e47df">

Мой код:

```
navigator.navigate { route in
            route
                .first(.tabs)
                .selectTab(of: UINavigationController.self, with: .index(1))
                .makeVisible()
}

```

**Comment by LevinIvan** [comment]
Проблему обнаружил в этих строчках когда:
```
        guard let vc = viewController?.navigationController else { return }
        navigator.navigate(from: vc) {
            $0.embedReplacing(makeTabsScreen())
        }
```

Если навигировать не из navigationController, тогда все работает ок:
```
    func setTabsScreen() async {
        navigator.navigate(to: showHomeRoute())
    }

    func showHomeRoute() -> ScreenWindowRoute {
        @IntercityInjected
        var tabsScreenFactory: TabsScreenFactoryProtocol

        return ScreenWindowRoute()
            .setRoot(to: tabsScreenFactory.makeTabsScreen())
            .makeKeyAndVisible()
    }
```

Но проблема в том, что мне нужен navigationController в этом кейсе.

**Comment by almazrafi** [comment]
Привет 👋

Не совсем понятно, как код из второго сообщения взаимодействует с кодом из первого сообщения?
Можете еще прислать логи с ошибками?

**Comment by LevinIvan** [comment]
Есть роутинг диплинка, который переключает на другой таб:
```
navigator.navigate { route in
            route
                .first(.tabs)
                .selectTab(of: UINavigationController.self, with: .index(1))
                .makeVisible()
}
```

Есть создание таб бара:
```
        guard let vc = viewController?.navigationController else { return }
        navigator.navigate(from: vc) {
            $0.embedReplacing(makeTabsScreen())
        }
```

Когда приходит диплинк и вызывается первый код для диплинки. Пишет, что контейнер TabBar не найден:
```
Info: Searching for a first container of UITabBarController type in UIWindow
Error: No container of UITabBarController type found for:
  ScreenFirstAction<UIWindow, UITabBarController>(predicate: container of UITabBarController type)
```

**Comment by almazrafi** [comment]
Скорее всего да, проблема из-за встраивания, нивелир по умолчанию не ищет кастомный контейнер в `children`.
Чтобы он начал там искал, нужно подписать ViewController, в который встраивается TabBarController, под протокол `ScreenIterableContainer`:

``` swift
extension SomeViewController: ScreenIterableContainer {

    public var nestedContainers: [ScreenContainer] {
        children
    }
}
```

Но хочется понять, какую проблему вы решаете, встраивая UITabBarController в другой контроллер? Возможно через средства Nivelir эту проблему можно решить и без встраивания.

**Comment by LevinIvan** [comment]
Да, это решение помогло. Спасибо!
