### ISSUE TITLE
is it possible to handle dismiss event by gesture swipe in host viewcontroller?

### ISSUE THREAD

**Issue by shalom-aviv** [hhru/Nivelir#108]

**Comment by almazrafi** [comment]
Hello 👋

Do you mean [UIHostingController](https://developer.apple.com/documentation/swiftui/uihostingcontroller)?

**Comment by shalom-aviv** [comment]
Sorry
I didn't express myself correctly

For example FirstViewController present SecondViewController
Does Nivelir has api to handle dismiss state of SecondViewController(by swipe/tap/etc)?

**Comment by almazrafi** [comment]
If you present the screen as a bottom sheet, then the closure `didDismiss` can be used to handle its dismissing event: https://github.com/hhru/Nivelir/blob/28f419c29bf2d8c28b94efb0508a8e464aea78e7/Sources/Addons/BottomSheet/BottomSheet.swift#L51

Bottom sheets can be displayed with the maximum possible height, for this you need to pass `.large` in the `detent` parameter: https://github.com/hhru/Nivelir/blob/28f419c29bf2d8c28b94efb0508a8e464aea78e7/Sources/Addons/BottomSheet/BottomSheet.swift#L35C9-L35C16

An alternative way is to use observers, in the demo project there is an example of their use with a similar case:
https://github.com/hhru/Nivelir/blob/28f419c29bf2d8c28b94efb0508a8e464aea78e7/Example/NivelirExample/Screens/Authorization/AuthorizationViewController.swift#L118
