### ISSUE TITLE
Using custom container view controllers with DefaultScreenIterator.

### ISSUE THREAD

**Issue by iON1k** [hhru/Nivelir#33]
`DefaultScreenIterator` works with standard controllers (such as `UINavigationController`, `UITabBarController`), but it doesn't work with non-native container view controllers (for example some custom bottom sheet controller or custom tab bar controller). 

Of course,  we can create our own implementation of `ScreenIterator`, but it doesn't look nice, because it 's almost copy-paste of `DefaultScreenIterator`. Moreover code is a bit tricky, so it's difficult to understand.

I think it would be a good idea to make `DefaultScreenIterator` more flexible and easier to extend. In my fork I made that [solution](https://github.com/iON1k/Nivelir/commit/ae91db284a2074f91aa19fc846a55e132eb5dfa3).

I can make PR or may be you have your own solution.

**Comment by iON1k** [comment]
So what do you think about such improvement?

**Comment by almazrafi** [comment]
Hello @iON1k 👋 

We have implemented the approach you suggested with a small renaming: 
https://github.com/hhru/Nivelir/blob/main/Sources/Screen/Container/ScreenIterableContainer.swift

Thank you 🙏
