### ISSUE TITLE
How to get route

### ISSUE THREAD

**Issue by makleso6** [hhru/Nivelir#58]
Hi! Thanks for lib!
How can I get first/last route in stack? 
Hierarchy
TabBar VC with 3 tabs -> Navigation VC with pushed view controllers ()

Code

```
return route
  .first(.tabs) 
  .selectedTab
  .last(.stack)
  .??Need to get first or last screen in Navigation VC stack??
```

**Comment by almazrafi** [comment]
Hello 👋 

You can use `stackRoot` and `stackTop` actions to get the first and last controller in the navigation controller stack:

``` swift
ScreenWindowRoute()
    .first(.tabs) 
    .selectedTab
    .last(.stack)
    .stackTop
//    .doSomething()
```

**Comment by makleso6** [comment]
Thanks!
