### ISSUE TITLE
Build failure in Xcode 14.0.1

### ISSUE THREAD

**Issue by baluhman** [hhru/Nivelir#87]
I have some issues when build Nivelir and Example app in Xcode 14, but it success and display some errors

<img width="379" alt="Screenshot 2022-10-12 at 14 16 30" src="https://user-images.githubusercontent.com/30830934/195316985-1401594b-9457-4dc5-be87-76f52addcf53.png">

I tried integrate Nivelir in my project by Carthage with Tuist but build failure

`*** Fetching Nivelir
*** Checking out Nivelir at "1.4.4"
*** No cache found for FirebaseAnalyticsBinary, building with all downstream dependencies
*** No cache found for FirebaseCrashlyticsBinary, building with all downstream dependencies
*** No cache found for Nivelir, building with all downstream dependencies
*** Downloading binary-only framework FirebaseAnalyticsBinary at "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
*** xcodebuild output can be found in /var/folders/mj/2bjgx7pd5jj7_vr_w39l2cl40000gp/T/carthage-xcodebuild.RQatES.log
*** Downloading binary-only framework FirebaseCrashlyticsBinary at "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"
*** Building scheme "Nivelir iOS" in Nivelir.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/o.krasnov/Projects/qa-devices/src/Tuist/Dependencies/Carthage/Checkouts/Nivelir/Nivelir.xcodeproj -scheme Nivelir\ iOS -configuration Release -derivedDataPath /Users/o.krasnov/Library/Caches/org.carthage.CarthageKit/DerivedData/14.0_14A309/Nivelir/1.4.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/mj/2bjgx7pd5jj7_vr_w39l2cl40000gp/T/Nivelir SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/o.krasnov/Projects/qa-devices/src/Tuist/Dependencies/Carthage/Checkouts/Nivelir)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/mj/2bjgx7pd5jj7_vr_w39l2cl40000gp/T/carthage-xcodebuild.RQatES.log
The 'carthage' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
Resolved cache profile 'Development' from Tuist's defaults
`FirebaseCrashlytics` is not a valid configured external dependency for platform ios
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose`

I switched to 1.4.6 and have same problem

**Comment by almazrafi** [comment]
Hello 👋 

It looks like the problem is in the integration of SwiftLint in the Nivelir project. 
We will investigate the problem and fix it in the near future.

Please try enabling the `SKIP_SWIFTLINES` option before executing the Carthage and Tuist commands:

``` sh
export SKIP_SWIFTLINT=YES
```

Maybe this will help solve the problem without waiting for a fix from us.

Thanks!

**Comment by baluhman** [comment]
Thanks👍🏼

**Comment by almazrafi** [comment]
We fixed the problem. Please try to upgrade to version `1.5.0`.
